### PR TITLE
TeamCity block messages

### PR DESCRIPTION
**Pull request by jozefizso**
Added support to write TeamCity service messages `message`, `blockOpened` and `blockClosed`.

### CODE REVIEW

**Comment by gep13** [comment]
@jozefizso do you know what version of Pester is being used by default on AppVeyor?  And is there a known issue as to why it is hanging?  Thanks!

**Comment by jozefizso** [comment]
According to this tweet we can use the older Pester 3.3.12 https://twitter.com/appveyor/status/683381915550789632

It fixed my branch build: https://ci.appveyor.com/project/jozefizso/psake-contrib/build/1.0.0-build-21

**Comment by dlwyatt** [comment]
I don't think it's a Pester problem. Something up with Chocolatey. Explicitly specifying version seems to work, even if it's latest (3.3.16)

**Comment by gep13** [comment]
@dlwyatt what issue are you seeing with Chocolatey?  Doesn't look like 3.3.16 has been pushed to Chocolatey.org yet.  If you are running into issues with Chocolatey, feel free to reach out to either myself or Rob, and we can help if we can.

**Comment by dlwyatt** [comment]
Sorry, meant 3.3.14. I was able to reproduce the hang of "cinst Pester" from my computer when someone tweeted about it, but "cinst Pester --version 3.3.14" worked fine for me.

**Comment by dlwyatt** [comment]
Just for giggles, you could try something like this in AppVeyor to download the latest version of Pester until this other problem goes away:

```posh
$version = @(clist pester) -match '^pester\s*([\d\.]+)$' -replace '[^\d\.]' | Select-Object -First 1
cinst pester --version $version
```

**Comment by gep13** [comment]
Hmm, this is very strange!  I have just been able to reproduce the issue locally on my machine as well :cry:

**Comment by gep13** [comment]
@jozefizso this Chocolatey Issue has been resolved: https://twitter.com/MSH_Dave/status/683677951536312321

Can you update this PR to remove the specific Pester version number, and I can get this pulled in and released?

Thanks!

**Comment by jozefizso** [comment]
I think I will create new pull request with squashed changes. That cinst bug fix should not be part of this changeset.

**Comment by gep13** [comment]
@jozefizso there is no need to create a new PR, just squash/rebase on your existing branch, adn this PR will be updated automagically :smile:

**Comment by gep13** [comment]
@jozefizso thanks again for your contributions! :+1:

**Pull request merged**
