### PR TITLE
Improved TeamCity service messages

### PR DESCRIPTION
**Pull request by jozefizso**
I have implemented commands for a few new TeamCity service messages and added unit tests for functions in `teamcity.ps1` using Pester framework.

Unit tests are automatically build on AppVeyor.

### CODE REVIEW

**Comment by gep13** [comment]
@jozefizso this looks like a great addition to the Service Messaging for TeamCity!  Thank you very much for your contribution!

I will set up appveyor and get this build running for this repository.

**Comment by gep13** [comment]
@jozefizso thanks again for your contribution!

https://ci.appveyor.com/project/GaryEwanPark/psake-contrib/build/1.0.0-build-1

**Comment by gep13** [comment]
@jozefizso just to let you know, this has now moved to here:

https://ci.appveyor.com/project/psake/psake-contrib/build/1.0.0-build-1

I created a new account in AppVeyor so that only psake projects show up there, rather than creating a project under my own account.

**Comment by jozefizso** [comment]
@gep13 thanks for the merge and setting up AppVeyor!

**Comment by gep13** [comment]
@not a problem at all.  I am waiting to hear from the current maintainer of the psake-contrib project on NuGet so I can push a new version, but not heard anything yet.

**Pull request merged**
